export const tmpFood = [
  {
    Title: "Yellow Cheese",
    Type: "Dairy",
    Description: "Blablbla",
    TimeToDeliver: "",
    Price: 11,
    DeliveryFee: 0.9,
    ProductRating: 4.7,
    IsProductPopular: false,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Apple",
    Type: "Fruits",
    Description: "Blalalaalala",
    TimeToDeliver: "",
    Price: 4,
    DeliveryFee: 0.4,
    ProductRating: 4,
    IsProductPopular: true,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Cucumber",
    Type: "Vegetable",
    Description: "blablalabl",
    TimeToDeliver: "",
    Price: 3,
    DeliveryFee: 0.3,
    ProductRating: 3.6,
    IsProductPopular: false,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Cinnabon",
    Type: "Bakery",
    Description: "cinnabon cinnabon",
    TimeToDeliver: "",
    Price: 6,
    DeliveryFee: 0.4,
    ProductRating: 4.2,
    IsProductPopular: false,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Beyond Burger",
    Type: "Vegan",
    Description: "Beyond Burger Beyond",
    TimeToDeliver: "",
    Price: 32,
    DeliveryFee: 2,
    ProductRating: 4.9,
    IsProductPopular: false,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Entrecote Steak",
    Type: "Meat",
    Description: "Entrecote Steak Entr",
    TimeToDeliver: "",
    Price: 70,
    DeliveryFee: 4,
    ProductRating: 5,
    IsProductPopular: true,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
  {
    Title: "Shrimps in cream",
    Type: "Sea",
    Description: "Shrimps in cream Shrimps",
    TimeToDeliver: "",
    Price: 110,
    DeliveryFee: 6,
    ProductRating: 4.6,
    IsProductPopular: true,
    image: "https://png.pngtree.com/png-vector/20210522/ourmid/pngtree-apple-is-naturally-thirsty-and-healthy-png-image_3323218.jpg",
  },
];
